### ISSUE TITLE
Avoid polygons does not work correctly

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice#95]
See below screenshots - it seems that the second polygon results in a route not found even though it does not touch a part of the route from the first screenshot

![screenshot from 2018-02-01 11-07-22](https://user-images.githubusercontent.com/7126643/35672887-3304fc36-0740-11e8-9a36-66ffcc01bad4.png)

![screenshot from 2018-02-01 11-07-48](https://user-images.githubusercontent.com/7126643/35672897-3b5d99b0-0740-11e8-86b2-752483a7a584.png)

**Comment by HendrikLeuschner** [comment]
@rabidllama , could you provide the API query for these two so I can begin fixing? Thanks in advance

**Comment by rabidllama** [comment]
https://api.openrouteservice.org/pdirections?api_key=58d904a497c67e00015b45fccaafa4432232493184c37adb81bb6c01&attributes=detourfactor|percentage&coordinates=8.684692,49.401968|8.690186,49.404299&elevation=true&extra_info=steepness|waytype|surface&geometry=true&geometry_format=geojson&instructions=true&instructions_format=html&language=en-US&options={"profile_params":{},"avoid_polygons":{"type":"Polygon","coordinates":[[["8.68161","49.40069"],["8.68797","49.40166"],["8.69338","49.40103"],["8.69168","49.39735"],["8.67936","49.39793"],["8.68161","49.40069"]]]}}&preference=shortest&profile=driving-car&units=m


https://api.openrouteservice.org/pdirections?api_key=58d904a497c67e00015b45fccaafa4432232493184c37adb81bb6c01&attributes=detourfactor|percentage&coordinates=8.684692,49.401968|8.690186,49.404299&elevation=true&extra_info=steepness|waytype|surface&geometry=true&geometry_format=geojson&instructions=true&instructions_format=html&language=en-US&options={"profile_params":{},"avoid_polygons":{"type":"Polygon","coordinates":[[["8.68161","49.40069"],["8.68810","49.40223"],["8.69338","49.40103"],["8.69168","49.39735"],["8.67936","49.39793"],["8.68161","49.40069"]]]}}&preference=shortest&profile=driving-car&units=m

**Comment by HendrikLeuschner** [comment]
Hey @rabidllama 
I tried this again locally and on maps.openrouteservice.org and I did not encounter the bug anymore. Might have been somehow resolved by something else. Can you check again and close if it works for you too?


![crop_polybug](https://user-images.githubusercontent.com/13396640/43206329-c0177e6e-9025-11e8-9629-9418d1de341f.jpg)

**Comment by rabidllama** [comment]
hmm, well it seems to be ok with the one polygon, but on live I still get issues when there is more than one polygon added. But the fix in #163 should correct the issue with multiple polygons when it is released
